feat: uploadprocessor grb
Informatievlaanderen/building-registry pull request #1014
Opened 2023-05-08 12:49 UTC by pgallik

2023-05-09 06:37 UTC, jvandaal commented on src/BuildingRegistry.Grb.Processor.Upload/UploadProcessor.cs
> +                var blobObject = await _blobClient.GetBlobAsync(jobName, stoppingToken);
Should we move this before setting the job/ticket to preparing/pending?

2023-05-09 06:40 UTC, jvandaal commented on src/BuildingRegistry.Grb.Processor.Upload/UploadProcessor.cs
> +                    var archiveValidator = new ZipArchiveValidator(GrbArchiveEntryStructure);
Can we inject the ZipArchiveValidator and the ZipArchiveTranslator through an interfaces? Then we can unit test the flows:
* Are all returned job records saved?
* Is the job status set to Error when a problem is returned from the validator?
* Is the ticket set tot Error when a problem is returned from the validator?

2023-05-09 06:41 UTC, jvandaal commented on src/BuildingRegistry.Grb.Processor.Upload/UploadProcessor.cs
> +                    await using var stream = await blobObject.OpenAsync(stoppingToken);
I'd gather all logic related to 
* checking if the blob is present,
* getting the blobObject
* and opening the blob object
in one place.

2023-05-09 07:14 UTC, ArneD commented on src/BuildingRegistry.Grb.Processor.Upload/ECSTaskOptions.cs
> +    public class ECSTaskOptions
Rename to `EcsTaskOptions`

2023-05-09 07:19 UTC, ArneD requested changes

2023-05-09 07:19 UTC, ArneD commented on src/BuildingRegistry.Grb.Processor.Upload/Zip/Core/FileProblem.cs
> +        public override bool Equals(object obj)
Can this method be moved up?
Then all `Equals` methods and `GetHashCode` methods are bunched together

2023-05-09 07:19 UTC, ArneD commented on src/BuildingRegistry.Grb.Processor.Upload/Zip/ZipArchiveProblems.cs
> +        }
Can you move this to the other `Equals` method?

2023-05-09 07:19 UTC, ArneD commented on src/BuildingRegistry.Grb.Processor.Upload/Zip/Exceptions/DbaseHeaderFormatException.cs
> +    public class DbaseHeaderFormatException : Exception
Implement `ISerializable` for all exceptions

2023-05-09 10:17 UTC, ArneD approved these changes

2023-05-09 10:17 UTC, ArneD commented on src/BuildingRegistry.Grb.Processor.Upload/Zip/Core/ProblemParameter.cs
> +        }
Move this one down so they are grouped.

2023-05-09 10:17 UTC, ArneD commented on src/BuildingRegistry.Grb.Processor.Upload/Zip/Exceptions/DbaseHeaderSchemaMismatchException.cs
> +namespace BuildingRegistry.Grb.Processor.Upload.Zip.Exceptions;
Blocked namespace, do it for the whole project to be sure.

2023-05-09 10:17 UTC, ArneD commented on src/BuildingRegistry.Grb.Processor.Upload/Zip/Exceptions/DbaseHeaderSchemaMismatchException.cs
> +public class DbaseHeaderSchemaMismatchException : Exception
See our Domain Exceptions.
Sealed, `[Serializable]` attribute.

2023-05-09 11:11 UTC, merged

2023-05-10 09:07 UTC, basisregisters-vlaanderen commented
:tada: This PR is included in version 3.75.0 :tada:

The release is available on [GitHub release](https://github.com/Informatievlaanderen/building-registry/releases/tag/v3.75.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: