Merge lambda
Informatievlaanderen/building-registry pull request #1075
Opened 2023-06-29 07:27 UTC by pgallik

2023-06-29 08:33 UTC, ArneD requested changes

2023-06-29 08:33 UTC, ArneD commented on src/BuildingRegistry.Api.BackOffice.Abstractions/Building/Validators/MergeBuildingRequestValidator.cs
> +            RuleFor(x => x.SamenvoegenGebouwen)
Do we need validation on the format of the PURI's given in `SamenvoegenGebouwen`

2023-06-29 12:09 UTC, jvandaal approved these changes

2023-06-29 12:10 UTC, merged

2023-06-30 15:06 UTC, basisregisters-vlaanderen commented
:tada: This PR is included in version 3.83.0 :tada:

The release is available on [GitHub release](https://github.com/Informatievlaanderen/building-registry/releases/tag/v3.83.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: