Integration db
Informatievlaanderen/building-registry pull request #1142
Opened 2024-01-12 16:13 UTC by jvandaal

2024-01-15 13:08 UTC, ArneD requested changes

2024-01-15 13:08 UTC, ArneD commented on src/BuildingRegistry.Projections.Integration/Building/LatestItem/BuildingLatestItem.cs
> +        public string CreatedOnAsString { get; set; }
Not needed here, only in version.

2024-01-15 13:08 UTC, ArneD commented on src/BuildingRegistry.Projections.Integration/BuildingUnit/LatestItem/BuildingUnitLatestItem.cs
> +        public string Function { get; set; }
OsloFunction + Function

2024-01-15 13:08 UTC, ArneD commented on src/BuildingRegistry.Projections.Integration/BuildingUnit/LatestItem/BuildingUnitLatestItem.cs
> +        public string GeometryMethod { get; set; }
OsloGeometryMethod + GeometryMethod

2024-01-15 13:08 UTC, ArneD commented on src/BuildingRegistry.Projections.Integration/BuildingUnit/LatestItem/BuildingUnitLatestItem.cs
> +        public string CreatedOnAsString { get; set; }
Not needed

2024-01-15 13:08 UTC, ArneD commented on src/BuildingRegistry.Projections.Integration/IntegrationContext.cs
> +        public async Task<string?> FindNiscode(Geometry sysGeometry, CancellationToken ct)
`FindNisCodeBy`?

2024-01-15 13:08 UTC, ArneD commented on src/BuildingRegistry.Projections.Integration/IntegrationContext.cs
> +        public async Task<string?> FindNiscode(Geometry sysGeometry, CancellationToken ct)
Or `FindMostIntersectingNisCodeBy` ?

2024-01-15 13:08 UTC, ArneD commented on src/BuildingRegistry.Projections.Integration/BuildingUnit/LatestItem/BuildingUnitAddress.cs
> +        }
Add index on separate properties

2024-01-15 13:14 UTC, emalfroy commented on src/BuildingRegistry.Projections.Integration/Building/LatestItem/BuildingLatestItem.cs
> +
Index on timestamp

2024-01-16 13:43 UTC, emalfroy approved these changes

2024-01-16 14:01 UTC, ArneD approved these changes

2024-01-16 14:01 UTC, merged