Refactor to async
Informatievlaanderen/building-registry pull request #709
Opened 2022-09-27 07:57 UTC by emalfroy

2022-09-27 09:25 UTC, pgallik commented on test/BuildingRegistry.Tests/BackOffice/Lambda/Building/BuildingLambdaHandlerTests.cs
> +                MockExceptionIdempotentCommandHandler(() => new IdempotencyException(string.Empty)).Object);
Setup the test with a mock exception idempotent handler without the exception.

2022-09-28 07:29 UTC, ArneD requested changes

2022-09-28 07:29 UTC, ArneD commented on src/BuildingRegistry.Api.BackOffice.Abstractions/Building/Requests/BackOfficeNotRealizeBuildingRequest.cs
> +    [DataContract(Name = "NietRealiseerGebouw", Namespace = "")]
remove datacontract

2022-09-28 07:29 UTC, ArneD commented on src/BuildingRegistry.Api.BackOffice.Abstractions/Building/Requests/BackOfficePlaceBuildingUnderConstructionRequest.cs
> +    [DataContract(Name = "GebouwInAanbouw", Namespace = "")]
remove `DataContract`

2022-09-28 07:29 UTC, ArneD commented on src/BuildingRegistry.Api.BackOffice.Abstractions/Building/Requests/BackOfficeRealizeBuildingRequest.cs
> +    [DataContract(Name = "RealiseerGebouw", Namespace = "")]
remove `DataContract`

2022-09-28 07:29 UTC, ArneD commented on src/BuildingRegistry.Api.BackOffice.Abstractions/BuildingUnit/Requests/BackOfficeNotRealizeBuildingUnitRequest.cs
> +    [DataContract(Name = "NietRealiseerGebouweenheid", Namespace = "")]
remove `DataContract`

2022-09-28 07:29 UTC, ArneD commented on src/BuildingRegistry.Api.BackOffice.Abstractions/BuildingUnit/Requests/BackOfficeRealizeBuildingUnitRequest.cs
> +    [DataContract(Name = "RealiseerGebouweenheid", Namespace = "")]
remove `DataContract`

2022-09-28 10:03 UTC, merged