feat: address commandhandling consumer
Informatievlaanderen/building-registry pull request #846
Opened 2022-12-21 08:30 UTC by emalfroy

2022-12-21 08:31 UTC, jvandaal commented on paket.dependencies
> +nuget Be.Vlaanderen.Basisregisters.MessageHandling.Kafka.Producer 4.6.1
Why do we need the producer here? We don't produce anything in building (yet)?

2022-12-21 15:00 UTC, ArneD requested changes

2022-12-21 15:00 UTC, ArneD commented on paket.dependencies
> +nuget Be.Vlaanderen.Basisregisters.MessageHandling.Kafka.Simple 4.7.0
Simple still needed?

2022-12-21 15:00 UTC, ArneD commented on src/BuildingRegistry.Consumer.Address/BuildingRegistry.Consumer.Address.csproj
> +
Remove

2022-12-21 15:17 UTC, jvandaal commented on src/BuildingRegistry.Consumer.Address/ConsumerAddress.cs
> +            IIdempotentConsumer<ConsumerAddressContext> kafkaIdemIdompotencyConsumer)
What does IdOmpotency mean? :-P

2022-12-22 08:10 UTC, jvandaal commented on paket.dependencies
> +nuget Be.Vlaanderen.Basisregisters.MessageHandling.Kafka.Simple 4.7.0
Removed and stills builds.

2022-12-22 08:11 UTC, jvandaal commented on src/BuildingRegistry.Consumer.Address/BuildingRegistry.Consumer.Address.csproj
> +
Removed.

2022-12-22 08:37 UTC, ArneD approved these changes

2022-12-22 08:37 UTC, merged

2022-12-22 09:44 UTC, basisregisters-vlaanderen commented
:tada: This PR is included in version 3.51.0 :tada:

The release is available on [GitHub release](https://github.com/Informatievlaanderen/building-registry/releases/tag/v3.51.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: